# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muonic_django', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pulse',
            name='pulse_width_ch0',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pulse',
            name='pulse_width_ch1',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pulse',
            name='pulse_width_ch2',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pulse',
            name='pulse_width_ch3',
            field=models.FloatField(null=True),
        ),
    ]
