# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muonic_django', '0002_auto_20170925_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
