# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muonic_django', '0003_run_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='count_ch0',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rate',
            name='count_ch1',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rate',
            name='count_ch2',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rate',
            name='count_ch3',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rate',
            name='count_cht',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
